insert into
    waste_donor(
        id,
        firstname,
        lastname,
        cell_number,
        residential_address,
        email,
        age,
        gender,
        id_number,
        user_password,
        verification
    )
values
    (
        1,
        'Sibusiso',
        'Nkosi',
        '0668034948',
        'Midrand',
        'sibusisonkosi0897@gmail.com',
        35,
        'Male',
        6208245617088,
        'Fwgr123',
        false
    );

insert into
    waste_donor(
        id,
        firstname,
        lastname,
        cell_number,
        residential_address,
        email,
        age,
        gender,
        id_number,
        user_password,
        verification
    )
values
    (
        2,
        'Jason',
        'Gama',
        '0812828250',
        'Midrand',
        'jasongama@gmail.com',
        25,
        'Male',
        7258245617088,
        'Fwgr123',
        false
    );